spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
websiteUrl: http://localhost:4242